"""empty message

Revision ID: 07f2ee1cf597
Revises: d56821672efe
Create Date: 2024-10-19 15:22:13.144330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f2ee1cf597'
down_revision = 'd56821672efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('total_call_slots', sa.Integer(), nullable=False),
    sa.Column('closure_percentage_goal', sa.Integer(), nullable=False),
    sa.Column('closure_percentage_projected', sa.Integer(), nullable=False),
    sa.Column('sales_value_projected', sa.Integer(), nullable=True, default=0),
    sa.Column('sales_value_goal', sa.Integer(), nullable=True, default=0),
    sa.Column('actual_sales_value', sa.Integer(), nullable=True, default=0),
    sa.Column('total_calls_made', sa.Integer(), nullable=True, default=0),
    sa.Column('total_calls_scheduled', sa.Integer(), nullable=True, default=0),
    sa.Column('total_sales_closed', sa.Integer(), nullable=True, default=0),
    sa.Column('total_deposits_collected', sa.Integer(), nullable=True, default=0),
    sa.Column('sales_agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_agent_id'], ['sales_agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_projections')
    # ### end Alembic commands ###
