"""empty message

Revision ID: 1cf9a1d15d1e
Revises: 4c41c746ac39
Create Date: 2024-06-17 12:56:26.987233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cf9a1d15d1e'
down_revision = '4c41c746ac39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('reregister_time',
               new_column_name='last_register_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('last_register_time',
               new_column_name='reregister_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
