"""empty message

Revision ID: 227e254446ab
Revises: 8c2927b31799
Create Date: 2024-11-13 13:11:09.149775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '227e254446ab'
down_revision = '8c2927b31799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
       batch_op.drop_column('callback_time')

    # ### end Alembic commands ###
