"""empty message

Revision ID: 2f97798b104e
Revises: abbc71165d5b
Create Date: 2024-03-26 13:52:34.986966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f97798b104e'
down_revision = 'abbc71165d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opportunity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'opportunity', ['opportunity_id'], ['id'])
        batch_op.create_foreign_key(None, 'sales_agent', ['mentor_id'], ['id'])

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign', mysql.VARCHAR(length=250), nullable=True))
        batch_op.alter_column('comment',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('opportunity_id')
        batch_op.drop_column('mentor_id')

    # ### end Alembic commands ###
