"""empty message

Revision ID: 36ddd57cbadc
Revises: 4764e9967291
Create Date: 2024-11-06 20:13:16.293581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36ddd57cbadc'
down_revision = '4764e9967291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_call_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('opportunity_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_status', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('lead_call_status', schema=None) as batch_op:
        batch_op.drop_column('active')
    # ### end Alembic commands ###
