"""empty message

Revision ID: 57c95062087a
Revises: 
Create Date: 2024-02-29 13:57:21.635806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c95062087a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_call_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lead_communication',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('campaign', sa.String(length=250), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('opportunity_status', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.Integer(), nullable=True),
    sa.Column('sales_agent', sa.Integer(), nullable=True),
    sa.Column('sales_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_status'], ['lead_call_status.id'], ),
    sa.ForeignKeyConstraint(['opportunity_status'], ['opportunity_status.id'], ),
    sa.ForeignKeyConstraint(['sales_agent'], ['sales_agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('receiver', sa.String(length=20), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('opportunity')
    op.drop_table('lead_communication')
    op.drop_table('templates')
    op.drop_table('sales_agent')
    op.drop_table('opportunity_status')
    op.drop_table('lead_call_status')
    op.drop_table('instances')
    # ### end Alembic commands ###
