"""empty message

Revision ID: 615694230186
Revises: 9fe0e5ca04ac
Create Date: 2024-10-22 11:46:55.216107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '615694230186'
down_revision = '9fe0e5ca04ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_projection_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing_spend', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_projection_config', schema=None) as batch_op:
        batch_op.drop_column('marketing_spend')

    # ### end Alembic commands ###
