"""empty message

Revision ID: 63da8105168b
Revises: 2f97798b104e
Create Date: 2024-03-27 19:55:02.462333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63da8105168b'
down_revision = '2f97798b104e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('appointment_time')

    # ### end Alembic commands ###
