"""empty message

Revision ID: 6b37d90235fa
Revises: 7175f90d3456
Create Date: 2024-10-28 20:32:31.181688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b37d90235fa'
down_revision = '7175f90d3456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['last_updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'sales_agent', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_updated_by')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
