"""empty message

Revision ID: 6bcd1f0915ed
Revises: 9ea7108f0425
Create Date: 2024-06-10 17:50:16.452107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bcd1f0915ed'
down_revision = '9ea7108f0425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_fbp', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ad_fbc', sa.String(length=500), nullable=True))
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('ad_fbc')
        batch_op.drop_column('ad_fbp')
    # ### end Alembic commands ###
