"""empty message

Revision ID: 76e43a2d5fd0
Revises: 1e0ad635858d
Create Date: 2024-10-22 15:59:45.067501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76e43a2d5fd0'
down_revision = '1e0ad635858d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_ad_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('ad_account_name', sa.String(length=255), nullable=False),
    sa.Column('ad_account_access_token', sa.String(length=255), nullable=False),
    sa.Column('ad_account_currency', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('app_secret', sa.String(length=255), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_ad_accounts')
    # ### end Alembic commands ###
