"""empty message

Revision ID: 791cd3c3972f
Revises: 2cc0579fcba8
Create Date: 2024-03-13 12:56:32.345952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '791cd3c3972f'
down_revision = '2cc0579fcba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_key'))

    op.drop_table('api_key')
    # ### end Alembic commands ###
