"""empty message

Revision ID: 7c0679605306
Revises: 004dab145c8d
Create Date: 2024-05-31 13:35:56.032924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c0679605306'
down_revision = '004dab145c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('ad_id', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('medium', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('medium')
        batch_op.drop_column('ad_id')
        batch_op.drop_column('ad_name')
    # ### end Alembic commands ###
