"""empty message

Revision ID: 88ba1ee26c61
Revises: 1cd0dbaaf58b
Create Date: 2024-04-05 10:09:16.563367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88ba1ee26c61'
down_revision = '1cd0dbaaf58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_call_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.String(length=25), nullable=True))

    with op.batch_alter_table('opportunity_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.String(length=25), nullable=True))

    with op.batch_alter_table('sales_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_agent', schema=None) as batch_op:
        batch_op.drop_column('text_color')

    with op.batch_alter_table('opportunity_status', schema=None) as batch_op:
        batch_op.drop_column('text_color')

    with op.batch_alter_table('lead_call_status', schema=None) as batch_op:
        batch_op.drop_column('text_color')

    # ### end Alembic commands ###
