"""empty message

Revision ID: 8c78a4c0bd06
Revises: 55211e692566
Create Date: 2024-07-03 20:23:19.314370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c78a4c0bd06'
down_revision = '55211e692566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded', sa.Boolean(), nullable=False))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('cancelled')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('refunded')
    # ### end Alembic commands ###
