"""empty message

Revision ID: 9b0f00a517ef
Revises: 36ddd57cbadc
Create Date: 2024-11-07 05:37:15.759799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b0f00a517ef'
down_revision = '36ddd57cbadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing table
    op.drop_table('user_role')
    
    # Create new table with compound primary key
    op.create_table('user_role',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_role_role_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_role_user_id'),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_user_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    # ### end Alembic commands ###
