"""empty message

Revision ID: 9fe0e5ca04ac
Revises: 2fedc2560008
Create Date: 2024-10-21 11:52:31.701860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fe0e5ca04ac'
down_revision = '2fedc2560008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_projection_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_up_rate_goal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('show_up_rate_projection', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_booked_goal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_booked_projection', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_projection_config', schema=None) as batch_op:
        batch_op.drop_column('appointment_booked_projection')
        batch_op.drop_column('appointment_booked_goal')
        batch_op.drop_column('show_up_rate_projection')
        batch_op.drop_column('show_up_rate_goal')
    # ### end Alembic commands ###
