"""empty message

Revision ID: abbc71165d5b
Revises: 791cd3c3972f
Create Date: 2024-03-15 09:54:31.129645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abbc71165d5b'
down_revision = '791cd3c3972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('career_challenge', sa.String(length=255), nullable=False),
    sa.Column('challenge_description', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=255), nullable=False),
    sa.Column('salary_range', sa.String(length=255), nullable=False),
    sa.Column('expected_salary', sa.String(length=255), nullable=False),
    sa.Column('current_employer', sa.String(length=255), nullable=False),
    sa.Column('financial_situation', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('max_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_name', sa.String(length=255), nullable=True),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('max_scores')
    op.drop_table('configs')
    op.drop_table('appointments')
    # ### end Alembic commands ###
