"""empty message

Revision ID: b4d3843c4c66
Revises: bc787d136e35
Create Date: 2024-09-19 12:50:28.306633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4d3843c4c66'
down_revision = 'bc787d136e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
