"""empty message

Revision ID: bc787d136e35
Revises: 46823a6e0d36
Create Date: 2024-09-07 04:54:53.413096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc787d136e35'
down_revision = '46823a6e0d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('same_state', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gst', sa.String(length=50), nullable=True))
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('gst')
        batch_op.drop_column('same_state')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
