"""empty message

Revision ID: cf202cdc717d
Revises: 6b37d90235fa
Create Date: 2024-10-30 08:59:23.452054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf202cdc717d'
down_revision = '6b37d90235fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optin_call_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('call_duration', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=255), nullable=False),
    sa.Column('call_status', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['sales_agent.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optin_call_record')
    # ### end Alembic commands ###
