"""empty message

Revision ID: d7a5725199e1
Revises: 9b392793b224
Create Date: 2024-07-30 17:45:51.416010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7a5725199e1'
down_revision = '9b392793b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('sales_agent', existing_type=mysql.INTEGER(), new_column_name='call_setter')
        batch_op.add_column(sa.Column('optin_caller', sa.Integer(), nullable=True))
        
        batch_op.create_foreign_key(None, 'sales_agent', ['optin_caller'], ['id'])
        
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_setter', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sales_agent', ['call_setter'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('call_setter')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('call_setter', new_column_name='sales_agent')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('optin_caller')
        
    # ### end Alembic commands ###
