"""empty message

Revision ID: e871040df128
Revises: 18166b4972b4
Create Date: 2024-07-05 05:00:57.459457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e871040df128'
down_revision = '17c3f6917803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_due',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False, default=0),
    sa.Column('cancelled', sa.Boolean(), nullable=False, default=0),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_due')
    # ### end Alembic commands ###
