"""empty message

Revision ID: f454d82e1057
Revises: 227e254446ab
Create Date: 2024-12-02 12:41:21.662085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f454d82e1057'
down_revision = '227e254446ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['mentor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mentor_id')

    # ### end Alembic commands ###
